version: 2.1
orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: print random text
          command: echo "HELLO"
      - discord/status:
          fail_only: true
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "https://discordapp.com/api/webhooks/964365127619055626/pSC2EgfUZS8rTNl2bpTIybtd4efb31dQSOpMhbrNKnNknqerOoqG021av5KH9Duniqx0"

  deploy_prod:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy code
          command: echo "deploying to production"
      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "https://discordapp.com/api/webhooks/964365127619055626/pSC2EgfUZS8rTNl2bpTIybtd4efb31dQSOpMhbrNKnNknqerOoqG021av5KH9Duniqx0"
          success_message: "**${CIRCLE_USERNAME}** deployed api to prod."
